/**
 * Auto-generated translation key types
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-i18n-types.ts
 * 
 * Run 'npm run generate:i18n' to regenerate this file
 */

export type TranslationKey =
  | 'auth.error'
  | 'auth.placeholder'
  | 'auth.question'
  | 'auth.subtitle'
  | 'auth.title'
  | 'auth.unlockButton'
  | 'common.close'
  | 'common.error'
  | 'common.loading'
  | 'common.switchLanguage'
  | 'language.croatian'
  | 'language.currentLanguage'
  | 'language.english'
  | 'language.switchTo'
  | 'map.resetView'
  | 'map.zoomIn'
  | 'map.zoomOut'
  | 'memory.closeButton'
  | 'memory.loading'
  | 'memory.videoLoadError'
  | 'memory.videoNotSupported'
  | 'story.memoryOf'
  | 'story.playButton'
  | 'story.progressLabel'
  | 'story.stopButton';
