#!/usr/bin/env node

/**
 * Type Generation Script for i18n
 * 
 * This script reads translation JSON files and generates TypeScript types
 * to ensure compile-time safety for translation keys.
 * 
 * Requirements: 2.5, 6.1, 6.4
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface TranslationMap {
  [key: string]: string | TranslationMap;
}

/**
 * Recursively extract all keys from a nested translation object
 * Returns keys in dot notation (e.g., "auth.title", "map.zoomIn")
 */
function extractKeys(obj: TranslationMap, prefix = ''): string[] {
  const keys: string[] = [];
  
  for (const [key, value] of Object.entries(obj)) {
    const fullKey = prefix ? `${prefix}.${key}` : key;
    
    if (typeof value === 'string') {
      keys.push(fullKey);
    } else if (typeof value === 'object' && value !== null) {
      keys.push(...extractKeys(value, fullKey));
    }
  }
  
  return keys.sort();
}

/**
 * Validate that two sets of keys are identical
 */
function validateKeys(hrKeys: string[], enKeys: string[]): void {
  const hrSet = new Set(hrKeys);
  const enSet = new Set(enKeys);
  
  const missingInEn = hrKeys.filter(k => !enSet.has(k));
  const missingInHr = enKeys.filter(k => !hrSet.has(k));
  
  if (missingInEn.length > 0) {
    throw new Error(
      `Missing keys in en.json:\n  ${missingInEn.join('\n  ')}`
    );
  }
  
  if (missingInHr.length > 0) {
    throw new Error(
      `Missing keys in hr.json:\n  ${missingInHr.join('\n  ')}`
    );
  }
}

/**
 * Generate TypeScript type definition file
 */
function generateTypeFile(keys: string[]): string {
  const typeUnion = keys.map(key => `  | '${key}'`).join('\n');
  
  return `/**
 * Auto-generated translation key types
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-i18n-types.ts
 * 
 * Run 'npm run generate:i18n' to regenerate this file
 */

export type TranslationKey =
${typeUnion};
`;
}

/**
 * Main execution
 */
function main(): void {
  try {
    console.log('🌍 Generating i18n types...');
    
    // Resolve paths
    const projectRoot = path.resolve(__dirname, '..');
    const hrPath = path.join(projectRoot, 'public', 'locales', 'hr.json');
    const enPath = path.join(projectRoot, 'public', 'locales', 'en.json');
    const outputPath = path.join(projectRoot, 'src', 'i18n', 'types.ts');
    
    // Read translation files
    console.log('  📖 Reading translation files...');
    const hrContent = fs.readFileSync(hrPath, 'utf-8');
    const enContent = fs.readFileSync(enPath, 'utf-8');
    
    // Parse JSON
    let hrTranslations: TranslationMap;
    let enTranslations: TranslationMap;
    
    try {
      hrTranslations = JSON.parse(hrContent);
    } catch (error) {
      throw new Error(`Invalid JSON in hr.json: ${error}`);
    }
    
    try {
      enTranslations = JSON.parse(enContent);
    } catch (error) {
      throw new Error(`Invalid JSON in en.json: ${error}`);
    }
    
    // Extract keys
    console.log('  🔍 Extracting translation keys...');
    const hrKeys = extractKeys(hrTranslations);
    const enKeys = extractKeys(enTranslations);
    
    console.log(`  ✓ Found ${hrKeys.length} keys in hr.json`);
    console.log(`  ✓ Found ${enKeys.length} keys in en.json`);
    
    // Validate key structure matches
    console.log('  🔎 Validating key structure...');
    validateKeys(hrKeys, enKeys);
    console.log('  ✓ Key structure matches across locales');
    
    // Generate type file
    console.log('  📝 Generating TypeScript types...');
    const typeFileContent = generateTypeFile(hrKeys);
    
    // Write to file
    fs.writeFileSync(outputPath, typeFileContent, 'utf-8');
    console.log(`  ✓ Types written to ${path.relative(projectRoot, outputPath)}`);
    
    console.log('✅ Type generation complete!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Type generation failed:');
    console.error(`  ${error instanceof Error ? error.message : String(error)}`);
    process.exit(1);
  }
}

main();
